Repository Tabeyouka/project_TABEYOUKA_react-deployment-repo, pull requests merged in 2023-07, with the labels that each got.

#17 test(tsconfig): enable noUnusedLocals and noUnusedParameters to test docker compose develop environment
  tsconfig.json
Labels: ⚙ Setting

#18 ✨ feat : Google social login feature added
  package.json
  public/tabeyoukaMiniLogo.png
  src/App.tsx
  src/components/layout/header/Logo.tsx
  src/components/layout/header/index.tsx
  src/components/layout/index.tsx
  src/components/socialLogin/GoogleLoginButton.tsx
  src/main.tsx
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  yarn.lock
Labels: ✨ Feature

#19 ✨ feat : Create profile page layout
  .gitignore
  package.json
  public/fukuoka.jpeg
  public/ramen.jpeg
  public/steak.webp
  src/App.tsx
  src/components/profile/UserMap.tsx
  src/components/profile/category/Categories.tsx
  src/components/profile/category/Category.tsx
  src/components/profile/modals/EditModal.tsx
  src/components/profile/review/Review.tsx
  src/components/profile/review/ReviewContainer.tsx
  src/components/profile/tab/TabPanel.tsx
  src/components/profile/tab/UserTab.tsx
  src/components/profile/userinfo/Bio.tsx
  src/components/profile/userinfo/Counter.tsx
  src/components/profile/userinfo/Name.tsx
  src/components/profile/userinfo/ProfileImage.tsx
  src/components/profile/userinfo/UserInfo.tsx
  src/pages/ProfilePage.tsx
  yarn.lock
Labels: 📬 API, 🎨 Html&css

#21 ✨ feat : search, creating store information layout
  .eslintrc.cjs
  src/App.tsx
  src/Router.tsx
  src/components/common/ImageSlider.tsx
  src/components/common/LowerLocation.tsx
  src/components/layout/header/GNB.tsx
  src/components/layout/header/Logo.tsx
  src/components/layout/header/index.tsx
  src/components/layout/index.tsx
  src/components/socialLogin/GoogleLoginButton.tsx
  src/components/ui/actionCard/infoCard.tsx
  src/components/ui/modal/CategoryModal.tsx
  src/components/ui/modal/FilterModal.tsx
  src/components/ui/modal/LocationModal.tsx
  src/components/ui/modal/MapModal.tsx
  src/components/ui/modal/RestaurantModal.tsx
  src/components/ui/modal/index.tsx
  src/hooks/useImageSlider.ts
  src/hooks/useInput.ts
  src/main.tsx
  src/pages/index.tsx
  src/pages/login.tsx
  src/pages/search.tsx
  src/pages/store.tsx
  src/types/hooks.interface.ts
Labels: 🔨 Refactor, ✨ Feature

#22 ✨ feat : implement story feature
  src/components/profile/MyButton.tsx
  src/components/profile/category/Categories.tsx
  src/components/profile/category/Category.tsx
  src/components/profile/category/Story.tsx
  src/components/profile/modals/AddStoryModal.tsx
  src/components/profile/modals/EditModal.tsx
  src/components/profile/modals/StoryEditModal.tsx
  src/components/profile/modals/StoryModal.tsx
  src/components/profile/modals/UserListItem.tsx
  src/components/profile/modals/UserModal.tsx
  src/components/profile/review/Review.tsx
  src/components/profile/review/ReviewContainer.tsx
  src/components/profile/userinfo/Counter.tsx
  src/components/profile/userinfo/Name.tsx
  src/components/profile/userinfo/UserInfo.tsx
  src/pages/ProfilePage.tsx
Labels: 📬 API, ✨ Feature

#23 ✨ feat : Add google maps
  package.json
  public/fukuoka.jpeg
  public/ramen.jpeg
  public/steak.webp
  src/components/layout/header/index.tsx
  src/components/profile/MyButton.tsx
  src/components/profile/UserMap.tsx
  src/components/profile/category/Categories.tsx
  src/components/profile/category/Story.tsx
  src/components/profile/map/Map.tsx
  src/components/profile/map/UserMap.tsx
  src/components/profile/modals/AddStoryModal.tsx
  src/components/profile/modals/EditModal.tsx
  src/components/profile/modals/StoryModal.tsx
  src/components/profile/modals/UserModal.tsx
  src/components/profile/review/Review.tsx
  src/components/profile/review/ReviewContainer.tsx
  src/components/profile/tab/TabPanel.tsx
  src/components/profile/tab/UserTab.tsx
  src/components/profile/userinfo/Bio.tsx
  src/components/profile/userinfo/Counter.tsx
  src/components/profile/userinfo/Name.tsx
  src/components/profile/userinfo/UserInfo.tsx
  src/components/socialLogin/GoogleLoginButton.tsx
  src/pages/ProfilePage.tsx
  src/pages/index.tsx
  src/pages/login.tsx
  src/pages/profile.tsx
  src/pages/search.tsx
  src/pages/store.tsx
  src/pages/unauthorized.tsx
  yarn.lock
Labels: ✨ Feature

#24 ✨ feat : Differentiate between Location and Restaurant to perform different functions
  package.json
  src/api/getRestaurant.ts
  src/api/search.ts
  src/categoryData.json
  src/components/common/InfoFooter.tsx
  src/components/common/LowerLocation.tsx
  src/components/common/MiddleLocation.tsx
  src/components/layout/header/MyPage.tsx
  src/components/layout/header/index.tsx
  src/components/socialLogin/GoogleLoginButton.tsx
  src/components/ui/actionCard/infoCard.tsx
  src/components/ui/modal/CategoryModal.tsx
  src/components/ui/modal/FilterModal.tsx
  src/components/ui/modal/LocationModal.tsx
  src/components/ui/modal/RestaurantModal.tsx
  src/components/ui/modal/index.tsx
  src/components/ui/table/index.tsx
  src/hooks/useGetCode.ts
  src/locationData.json
  src/main.tsx
  src/middleArea.json
  src/pages/index.tsx
  src/pages/login.tsx
  src/pages/search.tsx
  src/pages/store.tsx
  src/types/restaurant.interface.ts
  src/types/store.interface.ts
  yarn.lock
Labels: ✨ Feature, 🎨 Html&css

#25 🐛 fix : modify login request function
  package.json
  src/App.tsx
  src/components/layout/header/index.tsx
  src/components/profile/category/Categories.tsx
  src/components/profile/map/Map.tsx
  src/components/profile/modals/AddStoryModal.tsx
  src/components/profile/modals/EditModal.tsx
  src/components/profile/modals/StoryEditModal.tsx
  src/components/profile/modals/UserListItem.tsx
  src/components/profile/modals/UserModal.tsx
  src/components/profile/review/ReviewContainer.tsx
  src/components/profile/userinfo/Name.tsx
  src/components/profile/userinfo/UserInfo.tsx
  src/components/socialLogin/GoogleLoginButton.tsx
  src/pages/index.tsx
  src/pages/login.tsx
  src/pages/search.tsx
  src/pages/store.tsx
  yarn.lock
Labels: 📬 API, ✨ Feature

#28 Develop
  .github/workflows/main.yml
  src/components/review/RestaurantBanner.tsx
  src/components/review/ReviewItem.tsx
  src/components/review/modal/CreateReviewModal.tsx
  src/pages/review.tsx
  src/services/restaurant.service.ts
Labels: ✨ Feature

#29 ✨ feat : Create Google Maps based on search results
  src/components/common/InfoFooter.tsx
  src/components/common/MiddleLocation.tsx
  src/components/ui/actionCard/infoCard.tsx
  src/components/ui/modal/LocationModal.tsx
  src/components/ui/modal/MapModal.tsx
  src/components/ui/modal/RestaurantModal.tsx
  src/components/ui/table/index.tsx
  src/pages/index.tsx
  src/pages/search.tsx
  src/pages/store.tsx
Labels: ✨ Feature, 🎨 Html&css

#30 🎨 refactor : remove unnecessary code
  public/btn_google_signin_light_normal_web@2x.png
  src/components/layout/header/MyPage.tsx
  src/components/profile/category/Categories.tsx
  src/components/profile/modals/StoryEditModal.tsx
  src/components/profile/modals/StoryModal.tsx
  src/components/profile/review/Review.tsx
  src/components/profile/review/ReviewContainer.tsx
  src/components/profile/userinfo/Bio.tsx
  src/components/profile/userinfo/Name.tsx
  src/components/profile/userinfo/UserInfo.tsx
  src/components/socialLogin/GoogleLoginButton.tsx
  src/pages/login.tsx
Labels: 🐞 BugFix, 🔨 Refactor

#31 feat(RestaurantSelector): add RestaurantSelector component
  .github/workflows/main.yml
  src/components/common/carousel/ImageCarousel.tsx
  src/components/review/RestaurantBanner.tsx
  src/components/review/ReviewItem.tsx
  src/components/review/SelectedRestaurant.tsx
  src/components/review/modal/CreateReviewModal.tsx
  src/components/review/modal/RestaurantSelector.tsx
  src/hooks/usePage.ts
  src/pages/review.tsx
  src/pages/reviews.tsx
  src/services/restaurant.service.ts
  src/services/review.service.ts
  src/styles/ckeditor.css
  src/types/restaurant.interface.ts
  src/types/review.interface.ts
  src/utils/distances.ts
Labels: 🔨 Refactor, ✨ Feature

#32 fix: restored deleted file
  Dockerfile
  nginx.conf
Labels: 🌏 Deploy
