Repository Tabeyouka/project_TABEYOUKA_react-deployment-repo, pull requests merged in 2023-12, with the labels that each got.

#50 🎨 refactor : Remove unnecessary code & fix request path
  src/components/common/button/ProfileButton.tsx
  src/components/layout/header/index.tsx
  src/components/profile/category/Categories.tsx
  src/components/profile/information/Counter.tsx
  src/components/profile/modals/AddStoryModal.tsx
  src/components/profile/modals/EditModal.tsx
  src/components/profile/modals/StoryEditModal.tsx
  src/components/profile/modals/StoryModal.tsx
  src/components/profile/reviewtab/Review.tsx
  src/components/profile/reviewtab/ReviewContainer.tsx
  src/components/socialLogin/GoogleLoginButton.tsx
  src/pages/profile.tsx
Labels: 🐞 BugFix, 🔨 Refactor, 🎨 Html&css

#51 🎨 refactor : Change search window structure and update search button style
  src/components/store/body/BodyInfo.tsx
  src/components/store/body/MainInfo.tsx
  src/components/store/header/BasicInfo.tsx
  src/components/store/header/HeaderInfo.tsx
  src/components/ui/table/index.tsx
  src/pages/index.tsx
  src/types/restaurant.interface.ts
Labels: 🔨 Refactor, 🎨 Html&css

#52 🎨 refactor : Modify profile page style
  src/components/profile/tabs/UserTab.tsx
  src/pages/profile.tsx
Labels: 🔨 Refactor, 🎨 Html&css

#53 🎨 refactor : Modify profile page style
  src/components/profile/information/Counter.tsx
  src/components/profile/map/UserMap.tsx
  src/components/profile/reviewtab/Review.tsx
  src/pages/profile.tsx
Labels: 🎨 Html&css

#54 💄 style : Add responsive design
  src/components/profile/reviewtab/Review.tsx
  src/pages/profile.tsx
Labels: 🔨 Refactor, ✨ Feature, 🎨 Html&css

#55 💄 style : Modify profile page Category.tsx design
  src/components/common/button/DefaultButton.tsx
  src/components/profile/category/Categories.tsx
  src/components/profile/category/Category.tsx
  src/components/profile/category/Story.tsx
  src/components/profile/reviewtab/Review.tsx
  src/pages/profile.tsx
  src/styles/profilepage.css
Labels: 🔨 Refactor, 🎨 Html&css

#56 🎨 Refactor : Remove unnecessary code
  src/components/profile/modals/StoryModal.tsx
Labels: 🐞 BugFix, 🔨 Refactor
