Repository Tabeyouka/project_TABEYOUKA_react-deployment-repo, pull requests merged in 2023-08, with the labels that each got.

#33 🎨 refactor : Extract components
  src/components/store/body/BodyInfo.tsx
  src/components/store/body/MainInfo.tsx
  src/components/store/body/SideInfo.tsx
  src/components/store/body/index.tsx
  src/components/store/header/HeaderInfo.tsx
  src/components/store/header/index.tsx
  src/pages/store.tsx
Labels: 🔨 Refactor

#34 ✨ feat : implement infinite scroll
  src/App.tsx
  src/components/profile/category/Categories.tsx
  src/components/profile/category/Story.tsx
  src/components/profile/map/Map.tsx
  src/components/profile/modals/AddStoryModal.tsx
  src/components/profile/modals/EditModal.tsx
  src/components/profile/modals/StoryEditModal.tsx
  src/components/profile/modals/StoryModal.tsx
  src/components/profile/modals/UserModal.tsx
  src/components/profile/review/LoadingSpinner.tsx
  src/components/profile/review/ReviewContainer.tsx
  src/components/profile/tab/TabPanel.tsx
  src/components/profile/userinfo/Bio.tsx
  src/components/profile/userinfo/Name.tsx
  src/components/profile/userinfo/UserInfo.tsx
  src/pages/profile.tsx
  src/styles/loadingSpinner.css
Labels: ✨ Feature, 🎨 Html&css

#35 ✨ feat : Add loading while receiving current location
  src/components/common/button/ReSearchModalButton.tsx
  src/components/ui/modal/LocationModal.tsx
  src/pages/search.tsx
Labels: 🔨 Refactor, ✨ Feature

#36 🎨 refactor : Improve loading speed
  src/App.tsx
  src/components/profile/category/Categories.tsx
  src/components/profile/map/Map.tsx
  src/components/profile/map/UserMap.tsx
  src/components/profile/modals/AddStoryModal.tsx
  src/components/profile/modals/EditModal.tsx
  src/components/profile/modals/StoryEditModal.tsx
  src/components/profile/modals/StoryModal.tsx
  src/components/profile/modals/UserModal.tsx
  src/components/profile/review/ReviewContainer.tsx
  src/components/profile/userinfo/Name.tsx
  src/components/profile/userinfo/UserInfo.tsx
  src/components/socialLogin/GoogleLoginButton.tsx
  src/pages/profile.tsx
Labels: 🔨 Refactor

#37 💄 style : Add Reactive Design
  src/components/common/ImageSlider.tsx
  src/components/common/InfoFooter.tsx
  src/components/common/button/ModalButton.tsx
  src/components/common/button/ReSearchModalButton.tsx
  src/components/layout/header/Logo.tsx
  src/components/layout/header/index.tsx
  src/components/store/header/HeaderInfo.tsx
  src/components/store/header/index.tsx
  src/components/ui/modal/CategoryModal.tsx
  src/components/ui/modal/LocationModal.tsx
  src/components/ui/modal/MapModal.tsx
  src/components/ui/modal/RestaurantModal.tsx
  src/pages/index.tsx
  src/pages/login.tsx
  src/pages/search.tsx
Labels: 🎨 Html&css

#38 💄 style : Implement responsive design
  src/components/profile/modals/AddStoryModal.tsx
  src/components/profile/modals/EditModal.tsx
  src/components/profile/modals/StoryEditModal.tsx
  src/components/profile/modals/StoryModal.tsx
  src/components/profile/review/LoadingSpinner.tsx
  src/components/profile/review/ReviewContainer.tsx
  src/components/profile/userinfo/Counter.tsx
  src/components/profile/userinfo/ProfileImage.tsx
  src/components/profile/userinfo/UserInfo.tsx
  src/pages/profile.tsx
  src/styles/loadingSpinner.css
Labels: 🎨 Html&css

#39 🔨 chore : translate of language
  src/components/store/header/HeaderInfo.tsx
  src/components/ui/modal/CategoryModal.tsx
  src/components/ui/modal/LocationModal.tsx
  src/components/ui/modal/MapModal.tsx
  src/components/ui/modal/RestaurantModal.tsx
  src/pages/search.tsx
Labels: 🔨 Refactor
